name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      id: docker_build
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        docker build . --file Dockerfile --tag my-image-name:$IMAGE_TAG

    - name: Execute build script inside Docker container
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        docker run --rm my-image-name:$IMAGE_TAG ./build.sh
