name: Build Script CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up permissions for scripts
        run: |
          chmod +x ./get_tools.sh
          chmod +x ./build.sh

      - name: Run get_tools.sh
        run: ./get_toolchain.sh

      - name: Run build.sh
        run: ./build.sh
