name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  get-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Directory Structure
        run: |
          mkdir -p src/s32ds/source_release  # Create the necessary directory structure
      # - name: Run get_toolchain.sh
      #   run: |
      #     cd src/s32ds  # Change to the appropriate directory
      #     chmod +x ../get_toolchain.sh
      #     ../get_toolchain.sh

  build:
    runs-on: ubuntu-latest
    needs: get-tools  # This job depends on the get-tools job
    steps:
      - uses: actions/checkout@v4
      - name: Run build.sh
        run: |
          chmod +x ./build.sh
          ./build.sh
